### ISSUE TITLE
Add task for backfilling FASTQ metadata only

### ISSUE THREAD

**Issue by mbelmadani** [PavlidisLab/rnaseq-pipeline#4]
Some experiments may need to be re-downloaded for the only purpose of getting the FASTQ metadata. This could be made as a luigi task.

Additional considerations:
* Is it possible to speed this up by only downloading a small part of the file?
* Are there external meta data repos for GEO/SRA data? (e.g. MetaSRA, http://metasra.biostat.wisc.edu/api.html)
* Is it better to overwrite existing (obsolete or missing) metadata for historical purposes or append to it?

**Comment by arteymix** [comment]
Fixed in 3ef50276738d6bb98792d0bc6419c21ab9c85f9a

Generating batch info is triggered in SubmiExperimentToGemma only if the source is set to GEO.
